# Generated by Django 2.2.3 on 2019-07-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='1', max_length=12),
            preserve_default=False,
        ),
    ]
