# Generated by Django 2.2.3 on 2019-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtransitions',
            options={'ordering': ['modified_at', 'name']},
        ),
    ]
