# Generated by Django 2.2.3 on 2019-08-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190824_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdependency',
            name='dependent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_task_object', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task_object', to='tasks.Task'),
        ),
    ]
